import { type NextPage } from "next";
import Head from "next/head";
import LayoutPage from "../components/layout";

const PostPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LayoutPage>
        <div>Post View</div>
      </LayoutPage>
    </>
  );
};

export default PostPage;
